name: "Write or read AWS secrets"

on:
  #   push:
  #     branches:
  #       - test
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform"
        type: choice
        options:
          - Write AWS secrets and read them
          - Only read AWS secrets
      aws_access_key_id:
        description: "AWS Access Key ID"
        default: "Your access key id here"
        required: true
      aws_secret_access_key:
        description: "AWS Secret Access Key"
        default: "Your secret access key here"
        required: true
      aws_default_region:
        description: "AWS Default Region"
        default: "us-east-1"
        required: true

jobs:
  write_a_aws_secrets_and_read_them:
    name: "Write AWS secrets"
    if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'Write AWS secrets and read them')  }}    
    runs-on: ubuntu-latest
    steps:
      - name: "Write AWS_ACCESS_KEY_ID"
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: "AWS_ACCESS_KEY_ID"
          value: ${{ github.event.inputs.aws_access_key_id }}
          token: ${{ secrets.REPO_SECRET_WRITE_TOKEN }}

      - name: "Write AWS_SECRET_ACCESS_KEY"
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: "AWS_SECRET_ACCESS_KEY"
          value: ${{ github.event.inputs.aws_secret_access_key }}
          token: ${{ secrets.REPO_SECRET_WRITE_TOKEN }}

      - name: "Write AWS_DEFAULT_REGION"
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: "AWS_DEFAULT_REGION"
          value: ${{ github.event.inputs.aws_default_region }}
          token: ${{ secrets.REPO_SECRET_WRITE_TOKEN }}

      - name: "Read AWS secret"
        run: |
          SECRET="${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "The first 4 characters of the AWS Access Key ID are: ${SECRET:0:4}"
          SECRET="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "The first 4 characters of the AWS Secret Access Key are: ${SECRET:0:4}"
          SECRET="${{ secrets.AWS_DEFAULT_REGION }}"
          echo "The first 4 characters of the AWS Default Region are: ${SECRET:0:4}"

  only_read_aws_secrets:
    name: "Read AWS secret"
    if: ${{ github.event.inputs.action == 'Only read AWS secrets' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Read AWS secret"
        run: |
          SECRET="${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "The first 4 characters of the AWS Access Key ID are: ${SECRET:0:4}"
          SECRET="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "The first 4 characters of the AWS Secret Access Key are: ${SECRET:0:4}"
          SECRET="${{ secrets.AWS_DEFAULT_REGION }}"
          echo "The first 4 characters of the AWS Default Region are: ${SECRET:0:4}"